CREATE TABLE Sports (
	ID INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
	Question TEXT  NOT NULL,
	'0' TEXT  NOT NULL,
	'1' TEXT  NOT NULL,
	'2' TEXT  NOT NULL,
	'3' TEXT  NOT NULL,
	Answer INTEGER  NOT NULL
);

CREATE TABLE Arts (
	ID INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
	Question TEXT  NOT NULL,
	'0' TEXT  NOT NULL,
	'1' TEXT  NOT NULL,
	'2' TEXT  NOT NULL,
	'3' TEXT  NOT NULL,
	Answer INTEGER  NOT NULL
);

CREATE TABLE History (
	ID INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
	Question TEXT  NOT NULL,
	'0' TEXT  NOT NULL,
	'1' TEXT  NOT NULL,
	'2' TEXT  NOT NULL,
	'3' TEXT  NOT NULL,
	Answer INTEGER  NOT NULL
);

CREATE TABLE Places (
	ID INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
	Question TEXT  NOT NULL,
	'0' TEXT  NOT NULL,
	'1' TEXT  NOT NULL,
	'2' TEXT  NOT NULL,
	'3' TEXT  NOT NULL,
	Answer INTEGER  NOT NULL
);

CREATE TABLE Science (
	ID INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
	Question TEXT  NOT NULL,
	'0' TEXT  NOT NULL,
	'1' TEXT  NOT NULL,
	'2' TEXT  NOT NULL,
	'3' TEXT  NOT NULL,
	Answer INTEGER  NOT NULL
);